### ISSUE TITLE
Set up Github Actions to build PDF automatically

### ISSUE THREAD

**Issue by yungyuc** [yungyuc/bezierfoil#1]
We want to generate the PDF file nightly and per PR.  An example of the setup can be found in https://github.com/solvcon/mmnote/blob/master/.github/workflows/build_doc.yml .

**Comment by yungyuc** [comment]
@YenPeiChen07 Would you have time to do it?

**Comment by YenPeiChen07** [comment]
> @YenPeiChen07 Would you have time to do it?

Yes, I can do it.

**Comment by yungyuc** [comment]
Thanks.  Please create PRs for this task but you may merge before the code review is done, if you do not want to wait for it.  If we identify code issues in the code review, they can be handled in subsequent PRs.
